### ISSUE TITLE
List all indices Query

### ISSUE THREAD

**Issue by mmoreram** [apisearch-io/search-server#125]
We should add a new Query inside the system to list all existing indices, with the possibility of filtering by app. These are all the different subissues inside this issue.

- [x] Create the Query and QueryHandler - #133
- [x] Because the result is going to be provided by external plugins (like Elasticsearch), we should create a Domain structure (classes that define the model, like App with several Indices), and by adding middlewares, we should be able to populate this handler. Follow the same structure that is actually following the HealthCheck query. - #133
- [x] Create the controller, listening method GET. If the app_id is specified, then filter by it - #133
- [x] Create the console command, with the name `PrintIndicesCommand`. Should work as `PrintTokensCommand` works - #133
- [x] Add the endpoint inside the PHP client - https://github.com/apisearch-io/php-client/pull/41
- [x] Add the endpoint inside the Javascript client - https://github.com/apisearch-io/javascript-client/pull/22
- [x] Add the command in the Symfony Bundle. By passing a repository name, should list all indices - https://github.com/apisearch-io/apisearch-bundle/pull/30
- [x] Add query inside documentation

**Comment by mmoreram** [comment]
Doing by @hkulekci
